# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5965780d8c675b448375b5dfcc9ceca5ca9788d121ed81b3192ad694492e4dd2d37343c4b949b4514a546d627f09a1793912df21f8bdd7e1720e1270220ab07

test:
  secret_key_base: d7c51774e3bf5109c3e9ba69b6e76f9ad154cfbfe67b54d3787648606c8891854cb4e3dd1623456b0989f02d57d1c74cf5f3613929e1481c5067366c68393265

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
